# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-08 10:57
from __future__ import unicode_literals

import common.fields.dictionary
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=64)),
                ('group', models.CharField(blank=True, db_index=True, max_length=64)),
                ('properties', common.fields.dictionary.DictionaryField(blank=True, default=None, null=True)),
                ('datetime', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('date', models.DateField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
